version: '3.3'
services:
  db:
    image: postgres:11
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./northwind_data.sql:/docker-entrypoint-initdb.d/northwind_data.sql
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant
      POSTGRES_DB: northwind
  web:
    depends_on:
      - db
    build:
       context: .
       dockerfile: Dockerfile.txt
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/northwind
      SPRING_DATASOURCE_USERNAME: vagrant
      SPRING_DATASOURCE_PASSWORD: vagrant

volumes:
  db_data: